### ISSUE TITLE
Cannot install in languages other than English

### ISSUE THREAD

**Issue by GH2703** [lquessenberry/OpenSocialOnPantheon#1]
Unless you select English as the installation language, you would not get a successful installation.  All other languages will throw an error.  I have tried Espanol, Francois, Chinese, etc.  After pressing 'Save and continue' at the installation screen, it would immediately say Drupal has been installed, like the following in Espanol:

Drupal ya está instalado
Para iniciar de nuevo, debe limpiar su base de datos existente y copiar default.settings.php a settings.php. 
Para actualizar una instalación existente, proceda a actualizar script. 
Ver tu sitio existente. 

If you refresh the url, it would display a long error message.  Part of it is:

The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects (features.bundle.social) provided by social have unmet dependencies in Drupal\Core\Config\UnmetDependenciesException::create() (line 84 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php). ...

**Comment by lquessenberry** [comment]
@GH2703 Thanks for pointing this out. As you are aware, the issue tracker for this has been created at Drupal.org here:

https://www.drupal.org/node/2832103

I advise all seekers of a solution to this to follow that above link at Drupal.org for future solutions and troubleshooting.
